### ISSUE TITLE
Unable to run install.sh

### ISSUE THREAD

**Issue by S4nfs** [dmrub/nvidia-dev-ctl#1]
[Note: i change the foldername to gpumaster + i'm unfamiliar with python]

root@baremetal01:/home/s4nfs/gpumaster# chmod +x install.sh
root@baremetal01:/home/s4nfs/gpumaster# ./install.sh
+ sudo cp /root/home/s4nfs/gpumaster/nvidia-dev-ctl.service /usr/lib/systemd/system/
cp: cannot create regular file '/usr/lib/systemd/system/': Not a directory
root@baremetal01:/home/s4nfs/gpumaster#

**Comment by dmrub** [comment]
install.sh is not well documented and tested and is only needed to install a systemd service that automatically restores GPU configuration after a reboot. For this reason, it may not work properly.

But what is your Linux distribution ? Does it use systemd at all ?

**Comment by S4nfs** [comment]
I am using Ubuntu 18.04.5 LTS version but the systemd service is not installed in it. 

root@baremetal01:# systemctl status systemd
Unit systemd.service could not be found.


I am building a GUI to manage KVM GPUs and vGPUs and for the gpu management i am using this script to assign mdev devices to VMs and restore the same after reboot but i am not sure if this works because the install.sh failed to create that file.

**Comment by dmrub** [comment]
systemd is not a service, but a tool (https://en.wikipedia.org/wiki/Systemd), and since you have systemctl, it is installed.
Try to replace in script /etc/systemd/system/ with /usr/lib/systemd/system/.
See: 
https://medium.com/@benmorel/creating-a-linux-service-with-systemd-611b5c8b91d6

**Comment by S4nfs** [comment]
Its working but I am having trouble while attaching the mdev created to domain (newVM)
-----------------------------------------------------------------------------------------------------------------------------------
root@baremetal01:/home/s4nfs/gpubinder# ./nvidia-dev-ctl.py list-mdev -p 0000:af:00.0
MDEV_DEVICE_UUID                     PCI_ADDRESS  DEVICE      MDEV_NAME  VM_NAME
08672576-fad3-4a77-b5c3-33aa82e85915 0000:af:00.0 Device 1eb8 GRID T4-4Q        
4c9d7417-9e44-4a85-89e5-18016f238e99 0000:af:00.0 Device 1eb8 GRID T4-4Q Win2019
d26e2623-e659-43dd-9ec1-078c35d51909 0000:af:00.0 Device 1eb8 GRID T4-4Q  
      
root@baremetal01:/home/s4nfs/gpubinder# ./nvidia-dev-ctl.py attach-mdev d26e2623-e659-43dd-9ec1-078c35d51909 newVM
error: Failed to attach device from /tmp/tmp9d4z6fzz.xml
error: unsupported configuration: display property of device vfio-pci is not supported by this version of QEMU
Traceback (most recent call last):
  File "./nvidia-dev-ctl.py", line 2478, in <module>
    sys.exit(main())
  File "./nvidia-dev-ctl.py", line 2461, in main
    result = args.func(args)
  File "./nvidia-dev-ctl.py", line 2023, in attach_mdev
    dry_run=args.dry_run,
  File "./nvidia-dev-ctl.py", line 1452, in attach_mdev
    self.run_virsh(cmd)
  File "./nvidia-dev-ctl.py", line 1188, in run_virsh
    output = subprocess.check_output(virsh_command).decode("utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['virsh', 'attach-device', 'newVM', '--file', '/tmp/tmp9d4z6fzz.xml', '--config']' returned non-zero exit status 1.

**Comment by dmrub** [comment]
Try removing the `display='off'` option here (and possibly everywhere in the code if it helps):
https://github.com/dmrub/nvidia-dev-ctl/blob/2a64de5843607ee2933d6ba62a13a0ed3b80ad5f/nvidia-dev-ctl.py#L1432-L1436

I have tested this tool only on RHEL 7 and CentOS 7, because only on RHEL mdev devices from NVIDIA are supported

**Comment by S4nfs** [comment]
Yes it works, thanks for the help. 

root@baremetal01:/home/s4nfs/gpubinder# ./nvidia-dev-ctl.py list-mdev          
MDEV_DEVICE_UUID                     PCI_ADDRESS  DEVICE      MDEV_NAME  VM_NAME
08672576-fad3-4a77-b5c3-33aa82e85915 0000:af:00.0 Device 1eb8 GRID T4-4Q        
4c9d7417-9e44-4a85-89e5-18016f238e99 0000:af:00.0 Device 1eb8 GRID T4-4Q Win2019
d26e2623-e659-43dd-9ec1-078c35d51909 0000:af:00.0 Device 1eb8 GRID T4-4Q testvm

But i think mdev's only requirement is that Linux kernel must be 2.6.10 or later with the supported GPUs. I want to know which tool u use to manage the VMs, is it the classic virt-manager ?

**Comment by dmrub** [comment]
I use both virt-manager and virsh, but virt-manager does not support adding MDEV devices

**Comment by S4nfs** [comment]
How to add multiple mdev devices to the same VM, its throwing the error that device is already assigned. 

I want to attach my second nvidia vgpu [Tesla T4 8Q] which is of course under the same PCI. Is it possible?

**Comment by dmrub** [comment]
Can you provide a detailed error message?

**Comment by S4nfs** [comment]
root@baremetal01:/home/s4nfs/gpubinder# ./nvidia-dev-ctl.py attach-mdev --hotpl                                                                                        ug 11f13de7-96f5-4833-a47d-111e11294c45 Win2019
error: Failed to attach device from /tmp/tmp2qzpbpgy.xml
error: internal error: unable to execute QEMU command 'device_add': vfio error:                                                                                         11f13de7-96f5-4833-a47d-111e11294c45: error getting device from group 149: Input                                                                                        /output error
Traceback (most recent call last):
  File "./nvidia-dev-ctl.py", line 2478, in <module>
    sys.exit(main())
  File "./nvidia-dev-ctl.py", line 2461, in main
    result = args.func(args)
  File "./nvidia-dev-ctl.py", line 2023, in attach_mdev
    dry_run=args.dry_run,
  File "./nvidia-dev-ctl.py", line 1452, in attach_mdev
    self.run_virsh(cmd)
  File "./nvidia-dev-ctl.py", line 1188, in run_virsh
    output = subprocess.check_output(virsh_command).decode("utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['virsh', 'attach-device', 'Win2019', '-                                                                                        -file', '/tmp/tmp2qzpbpgy.xml', '--persistent']' returned non-zero exit status 1                                                                                        

### Here is the list of vgpu already attached and i want to attach my second one available T4-8Q vgpu which throws the above error.
![Screenshot (17)](https://user-images.githubusercontent.com/75138345/120077903-61b34f00-c0ca-11eb-98c8-3c9308f11c0b.png)

**Comment by dmrub** [comment]
I see in your command line the option --hotplug, even if I implemented it, the NVIDIA driver does not support hotplug of GPUs/vGPUs. Try shutting down your VM, then add a vGPU and start your VM. If you still have problems, run ./nvidia-dev-ctl.py with the -l INFO option and enter the output here.

**Comment by S4nfs** [comment]
Ok i'll try it with my vm shutoff but the hotplug is working as i tested it previously.

**Comment by S4nfs** [comment]
root@baremetal01:/home/s4nfs/gpubinder# virsh start Win2019
error: Failed to start domain Win2019
error: internal error: process exited while connecting to monitor: 2021-05-29T17:51:04.748758Z qemu-system-x86_64: -device vfio-pci,id=hostdev0,sysfsdev=/sys/bus/mdev/devices/26fec322-2f94-49f1-a531-f8dd612be79d,bus=pci.0,addr=0x8: vfio warning: 26fec322-2f94-49f1-a531-f8dd612be79d: Could not enable error recovery for the device
2021-05-29T17:51:04.769999Z qemu-system-x86_64: -device vfio-pci,id=hostdev1,sysfsdev=/sys/bus/mdev/devices/11f13de7-96f5-4833-a47d-111e11294c45,bus=pci.0,addr=0xa: vfio error: 11f13de7-96f5-4833-a47d-111e11294c45: error getting device from group 149: Input/output error
Verify all devices in group 149 are bound to vfio-<bus> or pci-stub and not already in use


root@baremetal01:/home/s4nfs/gpubinder# ./nvidia-dev-ctl.py -l INFO
PCI_ADDRESS  DEVICE      DEVICE_DRIVER MDEV_UUID                            MDEV_NAME  VM_NAME
0000:af:00.0 Device 1eb8 nvidia
0000:af:00.0 Device 1eb8 nvidia        11f13de7-96f5-4833-a47d-111e11294c45 GRID T4-8Q
0000:af:00.0 Device 1eb8 nvidia        26fec322-2f94-49f1-a531-f8dd612be79d GRID T4-8Q

virt-manager is showing the two mdev devices attached to my vm

**Comment by dmrub** [comment]
I had no such error and found only this in the NVIDIA forum:
https://forums.developer.nvidia.com/t/trouble-assigning-vgpu/162844

Regarding hot plug support:
https://docs.nvidia.com/grid/latest/grid-vgpu-release-notes-generic-linux-kvm/index.html#vgpu-hot-plug-not-supported

**Comment by S4nfs** [comment]
I think the gpu isn't supported for assigning multiple mdev devices to a single VM in KVM, maybe beacause they are under the same PCIe. This line "Verify all devices in group 149 are bound to vfio- or pci-stub and not already in use"

But i hotplugged the previously attached vgpu (in screenshot) just to test the hotplug support and it did shows the nvidia control panel just after 1 minutes.

**Comment by dmrub** [comment]
Multiple vGPUs are supported, but only NVIDIA can tell you what's going wrong:
https://docs.nvidia.com/grid/latest/grid-vgpu-release-notes-generic-linux-kvm/index.html#multiple-vgpu-support

**Comment by S4nfs** [comment]
Yes i attached multiple vGPUs to single vm when i was testing Tesla T4 in citrix's hypervisor, 

I'll try to find the problem.

**Comment by S4nfs** [comment]
Can you explain what's actually causing the error, Is it because of permission or am i using incorrect syntax as input command. 
Here,i am creating a mdev device and it's working on my shell but not in my php bootstrap.


Can't be permission related.
![Screenshot (31)](https://user-images.githubusercontent.com/75138345/123548230-8cec9500-d781-11eb-9692-844cb13895da.png)

**Comment by dmrub** [comment]
Python raises a PermissionError here, it looks to me like you are not running the script as root. But also check if the file /sys/class/mdev_bus/0000:af:00.0/mdev_supported_types/nvidia-233/create exists

**Comment by S4nfs** [comment]
FIXED: Yes it was some permission related error but on my shell_exec() function in php. 

www-data ALL=(ALL) NOPASSWD: ALL

**Comment by S4nfs** [comment]
Detach mdev command is not working for me with or without optional arguments, for detaching my vgpu i had to use the remove command. 

Here my vm (YoGo) is already off:

root@baremetal01:/var/www/html/arclight/gpubinder# ./nvidia-dev-ctl.py detach-mdev 6c3f44ab-1c9f-4ff2-9614-92be60e3fa9f YoGo
error: Failed to detach device from /tmp/tmpy5bsn8jm.xml
error: (device_definition):2: attributes construct error
<hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci''>
-------------------------------------------------------------------^
Traceback (most recent call last):
  File "./nvidia-dev-ctl.py", line 2477, in <module>
    sys.exit(main())
  File "./nvidia-dev-ctl.py", line 2460, in main
    result = args.func(args)
  File "./nvidia-dev-ctl.py", line 2035, in detach_mdev
    dry_run=args.dry_run,
  File "./nvidia-dev-ctl.py", line 1508, in detach_mdev
    self.run_virsh(cmd)
  File "./nvidia-dev-ctl.py", line 1187, in run_virsh
    output = subprocess.check_output(virsh_command).decode("utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['virsh', 'detach-device', 'YoGo', '--file', '/tmp/tmpy5bsn8jm.xml', '--config']' returned non-zero exit status 1.

**Comment by dmrub** [comment]
It's a bit strange, in the original code the XML is different than in your error message, there is the property `display='off'`:
https://github.com/dmrub/nvidia-dev-ctl/blob/5cca584ac07aa36c8660c220abe1ab3b02c72f6c/nvidia-dev-ctl.py#L1489 
And in your error message you have two consecutive quotes at the end of `model` property: `model='vfio-pci''`
The error message from virsh refers to XML, so maybe you just removed the display property in the source code and forgot to remove the last quote?

**Comment by S4nfs** [comment]
Yeah you're right, I'll try to figure out this.

**Comment by S4nfs** [comment]
No i changed nothing after this: https://github.com/dmrub/nvidia-dev-ctl/issues/1#issuecomment-835856084
Here's my code in nvidia-dev-ctl.py

```
<hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci'>
      <source>
            <address uuid='{}'/>
      </source>
</hostdev>
```

**Comment by dmrub** [comment]
I can't reproduce your problem, please try to run with DEBUG log mode:
```
$ ./nvidia-dev-ctl.py -l DEBUG attach-mdev ada782bb-dfd7-4573-a274-717c02be05a9 asr-vm-rhel-8.3
2021-08-25 16:38:35,836 INFO ./nvidia-dev-ctl.py:2440: Selected default URI for the virsh connection: qemu:///system
2021-08-25 16:38:35,908 DEBUG ./nvidia-dev-ctl.py:1187: Run: virsh -c qemu:///system dominfo asr-vm-rhel-8.3
2021-08-25 16:38:35,976 DEBUG ./nvidia-dev-ctl.py:1440: XML device file: 
<hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci' display='off'>
      <source>
            <address uuid='ada782bb-dfd7-4573-a274-717c02be05a9'/>
      </source>
</hostdev>
                
2021-08-25 16:38:35,976 INFO ./nvidia-dev-ctl.py:1444: Attach mdev device ada782bb-dfd7-4573-a274-717c02be05a9 to domain asr-vm-rhel-8.3
2021-08-25 16:38:35,977 DEBUG ./nvidia-dev-ctl.py:1187: Run: virsh -c qemu:///system attach-device asr-vm-rhel-8.3 --file /tmp/tmpb1zpwt9p.xml --config


$ ./nvidia-dev-ctl.py -l DEBUG detach-mdev ada782bb-dfd7-4573-a274-717c02be05a9 asr-vm-rhel-8.3
2021-08-25 16:38:50,304 INFO ./nvidia-dev-ctl.py:2440: Selected default URI for the virsh connection: qemu:///system
2021-08-25 16:38:50,377 DEBUG ./nvidia-dev-ctl.py:1187: Run: virsh -c qemu:///system dominfo asr-vm-rhel-8.3
2021-08-25 16:38:50,429 DEBUG ./nvidia-dev-ctl.py:1497: XML device file: 
<hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci' display='off'>
      <source>
            <address uuid='ada782bb-dfd7-4573-a274-717c02be05a9'/>
      </source>
</hostdev>
                
2021-08-25 16:38:50,430 INFO ./nvidia-dev-ctl.py:1501: Detach mdev device ada782bb-dfd7-4573-a274-717c02be05a9 from domain asr-vm-rhel-8.3
2021-08-25 16:38:50,430 DEBUG ./nvidia-dev-ctl.py:1187: Run: virsh -c qemu:///system detach-device asr-vm-rhel-8.3 --file /tmp/tmp7a28swdf.xml --config
```

**Comment by dmrub** [comment]
I get exactly your error message when I remove the display property but leave the last quote !!! :
```python
            with tempfile.NamedTemporaryFile(suffix=".xml", mode="w+t", delete=False) as tmp_dev:
                dev_xml = """
<hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci''> # <------- HERE
      <source>
            <address uuid='{}'/>
      </source>
</hostdev>

```
Then detach-mdev produces this:
```
$ ./nvidia-dev-ctl.py -l DEBUG detach-mdev ada782bb-dfd7-4573-a274-717c02be05a9 asr-vm-rhel-8.3
2021-08-25 16:44:58,210 INFO ./nvidia-dev-ctl.py:2440: Selected default URI for the virsh connection: qemu:///system
2021-08-25 16:44:58,279 DEBUG ./nvidia-dev-ctl.py:1187: Run: virsh -c qemu:///system dominfo asr-vm-rhel-8.3
2021-08-25 16:44:58,339 DEBUG ./nvidia-dev-ctl.py:1497: XML device file: 
<hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci''>
      <source>
            <address uuid='ada782bb-dfd7-4573-a274-717c02be05a9'/>
      </source>
</hostdev>
                
2021-08-25 16:44:58,339 INFO ./nvidia-dev-ctl.py:1501: Detach mdev device ada782bb-dfd7-4573-a274-717c02be05a9 from domain asr-vm-rhel-8.3
2021-08-25 16:44:58,339 DEBUG ./nvidia-dev-ctl.py:1187: Run: virsh -c qemu:///system detach-device asr-vm-rhel-8.3 --file /tmp/tmpermme7c6.xml --config
error: Failed to detach device from /tmp/tmpermme7c6.xml
error: (device_definition):2: attributes construct error
<hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci''>
-------------------------------------------------------------------^
Traceback (most recent call last):
  File "./nvidia-dev-ctl.py", line 2478, in <module>
    sys.exit(main())
  File "./nvidia-dev-ctl.py", line 2461, in main
    result = args.func(args)
  File "./nvidia-dev-ctl.py", line 2036, in detach_mdev
    dry_run=args.dry_run,
  File "./nvidia-dev-ctl.py", line 1509, in detach_mdev
    self.run_virsh(cmd)
  File "./nvidia-dev-ctl.py", line 1188, in run_virsh
    output = subprocess.check_output(virsh_command).decode("utf-8")
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['virsh', '-c', 'qemu:///system', 'detach-device', 'asr-vm-rhel-8.3', '--file', '/tmp/tmpermme7c6.xml', '--config']' returned non-zero exit status 1.

```

**Comment by S4nfs** [comment]
Fixed: i do the same error, i forgot that there are four of these lines and i previously removed the display property from the second one.

**Comment by S4nfs** [comment]
I am not getting any output after executing 
./nvidia-dev-ctl.py attach-pci 0000:af:00.0 Win2019



Is it due to unavailable driver or something else becoz i had already installed vgpu driver on the host
./nvidia-dev-ctl.py list-pci -o table
PCI_ADDRESS  DEVICE      DEVICE_DRIVER
0000:af:00.0 Device 1eb8 no driver

**Comment by S4nfs** [comment]
I need to switch from VGPU to GPU pass through but i am only getting this output after binding the vfio drivers
./nvidia-dev-ctl.py -l INFO bind-driver vfio-pci 0000:af:00.0
2021-10-30 12:51:04,501 INFO Override driver vfio-pci for PCI device 0000:af:00.0


here's all my devices and it's still showing no drivers
PCI_ADDRESS  DEVICE      DEVICE_DRIVER 
0000:af:00.0 Device 1eb8 no driver

**Comment by dmrub** [comment]
Please run with option -l DEBUG instead of -l INFO and post all output. I assume that you start the program as root or with sudo.

**Comment by S4nfs** [comment]
If i am not wrong the `bind-driver` command is optional becoz when i try to GPU pass through the second time it automatically bind the vfio driver to my PCI device with just `attach-pci` Last time i ran the `bind driver` first as it was showing nvidia instead of vfio under DEVICE_DRIVER

**Comment by dmrub** [comment]
Yes, the attach-pci command uses bind_driver function with vfio-pci argument at the beginning
